use crate::ir::{IR, Instruction, Operand, Value, Expression, FunctionDefinition};

pub struct RustGenerator;

impl RustGenerator {
    pub fn generate(ir: &IR) -> String {
        let mut rust = String::from("// Auto-generated by Tama\n");
        rust.push_str("#![no_std]\n");
        rust.push_str("use soroban_sdk::{contract, contractimpl, Env, symbol_short};\n\n");
        rust.push_str("#[contract]\npub struct Contract;\n\n#[contractimpl]\nimpl Contract {\n");
        
        for func in &ir.functions {
            rust.push_str(&Self::generate_function(func));
        }
        
        rust.push_str("}\n");
        rust
    }

    fn generate_function(func: &FunctionDefinition) -> String {
        let mut rust = format!("    pub fn {}(env: Env) {{\n", func.name);
        
        for inst in &func.body {
            match inst {
                Instruction::LoadStorage { dest, key } => {
                    rust.push_str(&format!(
                        "        let {} = env.storage().instance().get::<_, i64>(&symbol_short!(\"{}\")).unwrap_or(0);\n",
                        dest, key
                    ));
                }
                Instruction::StoreStorage { key, value } => {
                    let val_str = match value {
                        Operand::Const(Value::Int(i)) => i.to_string(),
                        Operand::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                        Operand::Var(name) => name.clone(),
                    };
                    rust.push_str(&format!(
                        "        env.storage().instance().set(&symbol_short!(\"{}\"), &{});\n",
                        key, val_str
                    ));
                }
                Instruction::SetVar { name, value } => {
                    let val_str = match value {
                        Expression::Const(Value::Int(i)) => i.to_string(),
                        Expression::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                        Expression::Var(v) => v.clone(),
                        Expression::Add(l, r) => {
                            let l_str = match l {
                                Operand::Const(Value::Int(i)) => i.to_string(),
                                Operand::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                                Operand::Var(name) => name.clone(),
                            };
                            let r_str = match r {
                                Operand::Const(Value::Int(i)) => i.to_string(),
                                Operand::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                                Operand::Var(name) => name.clone(),
                            };
                            format!("{} + {}", l_str, r_str)
                        }
                        Expression::Sub(l, r) => {
                            let l_str = match l {
                                Operand::Const(Value::Int(i)) => i.to_string(),
                                Operand::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                                Operand::Var(name) => name.clone(),
                            };
                            let r_str = match r {
                                Operand::Const(Value::Int(i)) => i.to_string(),
                                Operand::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                                Operand::Var(name) => name.clone(),
                            };
                            format!("{} - {}", l_str, r_str)
                        }
                        Expression::Mul(l, r) => {
                            let l_str = match l {
                                Operand::Const(Value::Int(i)) => i.to_string(),
                                Operand::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                                Operand::Var(name) => name.clone(),
                            };
                            let r_str = match r {
                                Operand::Const(Value::Int(i)) => i.to_string(),
                                Operand::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                                Operand::Var(name) => name.clone(),
                            };
                            format!("{} * {}", l_str, r_str)
                        }
                        Expression::Call(name, args) => {
                            let args_str: Vec<String> = args.iter().map(|arg| match arg {
                                Operand::Const(Value::Int(i)) => i.to_string(),
                                Operand::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                                Operand::Var(name) => name.clone(),
                            }).collect();
                            format!("{}({})", name, args_str.join(", "))
                        }
                    };
                    rust.push_str(&format!("        let {} = {};\n", name, val_str));
                }
                Instruction::Add { dest, left, right } => {
                    let l_str = match left {
                        Operand::Const(Value::Int(i)) => i.to_string(),
                        Operand::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                        Operand::Var(name) => name.clone(),
                    };
                    let r_str = match right {
                        Operand::Const(Value::Int(i)) => i.to_string(),
                        Operand::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                        Operand::Var(name) => name.clone(),
                    };
                    rust.push_str(&format!("        let {} = {} + {};\n", dest, l_str, r_str));
                }
                Instruction::Sub { dest, left, right } => {
                    let l_str = match left {
                        Operand::Const(Value::Int(i)) => i.to_string(),
                        Operand::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                        Operand::Var(name) => name.clone(),
                    };
                    let r_str = match right {
                        Operand::Const(Value::Int(i)) => i.to_string(),
                        Operand::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                        Operand::Var(name) => name.clone(),
                    };
                    rust.push_str(&format!("        let {} = {} - {};\n", dest, l_str, r_str));
                }
                Instruction::Mul { dest, left, right } => {
                    let l_str = match left {
                        Operand::Const(Value::Int(i)) => i.to_string(),
                        Operand::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                        Operand::Var(name) => name.clone(),
                    };
                    let r_str = match right {
                        Operand::Const(Value::Int(i)) => i.to_string(),
                        Operand::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                        Operand::Var(name) => name.clone(),
                    };
                    rust.push_str(&format!("        let {} = {} * {};\n", dest, l_str, r_str));
                }
                Instruction::Return { value } => {
                    if let Some(val) = value {
                        let val_str = match val {
                            Operand::Const(Value::Int(i)) => i.to_string(),
                            Operand::Const(Value::String(s)) => format!("symbol_short!(\"{}\")", s),
                            Operand::Var(name) => name.clone(),
                        };
                        rust.push_str(&format!("        return {};\n", val_str));
                    } else {
                        rust.push_str("        return;\n");
                    }
                }
            }
        }
        
        rust.push_str("    }\n");
        rust
    }
}
